### PR TITLE
Fix #50 - Update ledger library to accommodate chainIDs above 108

### LINKED ISSUE #50: Ledger dependencies bump to 5.36.0
LedgerHQ has [released 5.36.0](https://www.npmjs.com/search?q=%40ledgerhq) of all dependencies which includes support for chainIDs above 108. Please bump dependencies on https://github.com/MetaMask/eth-ledger-bridge-keyring/tree/gh-pages . CC @brunobar79

### PR DESCRIPTION
**Pull request by darkwing**
Fixes #50 

Updates our Ledger libraries to more recent version, allowing for chains over 108 to be supported, as fixed by Ledger here: 

https://github.com/LedgerHQ/ledgerjs/commit/bab3188bf5168f9e6f0f883e3b6dabc2e534537b

### CODE REVIEW

**Comment by darkwing** [comment]
This likely also fixes https://github.com/MetaMask/metamask-extension/issues/10240

**Review by Gudahtt — APPROVED** [review]
LGTM! Tested various things with a Ledger Nano S. Seems to work.

**Comment by Gudahtt** [comment]
The keyring needs further updates to support EIP-712 though, so https://github.com/MetaMask/metamask-extension/issues/10240 remains unresolved. See this function: https://github.com/MetaMask/eth-ledger-bridge-keyring/blob/master/index.js#L254

**Comment by btchip** [comment]
https://github.com/LedgerHQ/ledger-live-common/blob/master/src/families/ethereum/hw-signMessage.js might help to fill in the gaps in EIP 712 implementation

**Comment by darkwing** [comment]
Using the following test network, and a Ledger Nano X, I was able to review and confirm a transaction:

Name: heco-testnet
RPC URL: https://http-testnet.hecochain.com
Chain: 256
Block URL: https://scan-testnet.hecochain.com/

**Review by tmashuang — APPROVED** [review]
LGTM

**Comment by traderdeploy** [comment]
Hi @tmashuang,

When will this be merged to the metamask extention?  looks like the extension are still using 0.2.6?

**Comment by hoffer** [comment]
Hi @tmashuang,

When will this be merged to the metamask extention? looks like the extension are still using 0.2.6?

**Comment by darkwing** [comment]
@hoffer This was merged and immediately live -- it does not require bundling with MetaMask.

If you are experiencing a problem, please open a new issue with steps to reproduce.  Thank you!

**Comment by hoffer** [comment]
> @hoffer This was merged and immediately live -- it does not require bundling with MetaMask.
> 
> If you are experiencing a problem, please open a new issue with steps to reproduce. Thank you!

it works now. Thanks a lot!!!

**Pull request merged**
