### PR TITLE
Update to 0.4.0

### PR DESCRIPTION
**Pull request by darkwing**
* Includes the required wiring to allow switching between Ledger Live and U2F connections to the Ledger.
* Upgrade of the ethereumjs-util library to 7.0.9
* Renamed `_isBIP44` to more intelligible `_isLedgerLiveHdPath`
* Repo standardization which require minimum version of Node 12 and switch to `yarn`

### CODE REVIEW

**Comment by Gudahtt** [comment]
Looks good! It'd be great to get a list of changes for this version though, at least in the PR description (since there is no changelog)

**Comment by Gudahtt** [comment]
The repo standardization in #66 bumped the minimum Node.js version. As a breaking change, that should definitely be reflected in the changelog.

**Comment by darkwing** [comment]
Updated!

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Comment by darkwing** [comment]
* Includes the required wiring to allow switching between Ledger Live and U2F connections to the Ledger.
* Upgrade of the ethereumjs-util library to 7.0.9
* Renamed _isBIP44 to more intelligible _isLedgerLiveHdPath
* Repo standardization which require minimum version of Node 12 and switch to yarn

**Comment by Gudahtt** [comment]
>A new version of the package @metamask/eth-ledger-bridge-keyring (0.4.0) was published at 2021-04-20T17:18:35.383Z from
[redacted]. The shasum of this package was 764834adf146fc86ab7688a6c8f1e08708ed0d71.

**Review by Reclick55 — COMMENTED** [review]
How that possible

**Pull request merged**
