### PR TITLE
Update Ledger packages; Remove Babel Polyfill;

### PR DESCRIPTION
**Pull request by sterlu**
- Update Ledger packages - primarily to include https://github.com/LedgerHQ/ledgerjs/pull/514 (We've had complaints from users that some transactions were shown as rejected even though they confirmed them on the device. Judging from some limited testing, it seems to have been fixed by this PR). 
- Remove Babel Polyfill - not required since https://github.com/LedgerHQ/ledgerjs/releases/tag/v5.0.0
- Rebuild bundle using `npm run build`

### CODE REVIEW

**Comment by martinkou** [comment]
+1 on this. This is needed for using the ETH2 staking contract w/ Ledger through MetaMask.

**Comment by gradoj** [comment]
Can someone tell me what is going on with this? Seems to be stalled since Aug

**Comment by 3cl1ps** [comment]
waiting for it too to start eth stake
this tool is not working for me https://github.com/LefterisJP/eth2_deposit_tx_maker

**Comment by sterlu** [comment]
It's worth noting that integrating directly with the Ledger sdk (instead of
relying on metamask) works fine, albeit bringing a relatively more
complicated provider setup. I believe 0x has a subprovider package for
Ledger too, although I can't vouch for it.

**Comment by damiantw** [comment]
+1 can this please be merged?

**Comment by elegantalchemist** [comment]
Can this be merged? Without this merge staking on ETH is dead and previously staked stuff cannot be accessed. This is a pretty critical fault.

**Comment by mudgen** [comment]
Yes, please merge this or otherwise fix the ledger problem.

**Comment by darkwing** [comment]
Superceded by https://github.com/MetaMask/eth-ledger-bridge-keyring/pull/53 , thank you so much for your contribution!

**Pull request closed without merging**
